apiVersion: v1
kind: Namespace
metadata:
  name: fastfood-api
---
# deployment.yaml
# Define o Deployment da API com requests/limits para permitir HPA
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastfood-api
  namespace: fastfood-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastfood-api
  template:
    metadata:
      labels:
        app: fastfood-api
    spec:
      containers:
        - name: fastfood-api
          image: 939530529281.dkr.ecr.us-east-1.amazonaws.com/fastfood-repository:latest  # Imagem carregada no Minikube
          # imagePullPolicy: Never #Instrui o Kubernetes a nunca tentar puxar a imagem do Docker Hub, e sim usar a imagem que já está carregada no cluster (via minikube image load).
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: ENABLE_SWAGGER
              value: "true"
            - name: ASPNETCORE_URLS
              value: "http://+:80"
            - name: connectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: DB_CONNECTION_STRING