apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: fastfood-db
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None  # Ou remova essa linha para permitir DNS interno