apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: fastfood-api
type: Opaque
data:
  # DB_CONNECTION_STRING: "Server=mysql.fastfood-db.svc.cluster.local;Port=3306;Database=FastFoodDb;User=root;Password=fastfood@123;"
  DB_CONNECTION_STRING: U2VydmVyPW15c3FsLmZhc3Rmb29kLWRiLnN2Yy5jbHVzdGVyLmxvY2FsO1BvcnQ9MzMwNjtEYXRhYmFzZT1GYXN0Rm9vZERiO1VzZXI9cm9vdDtQYXNzd29yZD1mYXN0Zm9vZEAxMjM7